<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CompetitionManager.Application/CompetitionManager.Application.csproj" />
    <ProjectReference Include="../CompetitionManager.Domain/CompetitionManager.Domain.csproj" />
    <ProjectReference Include="../CompetitionManager.Infrastructure/CompetitionManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
